[package]
name = "tui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.28.1"
tokio = { version = "1.39.3", features = ["full"] }
protocol = { path = "../protocol" }
youtube = { path = "../youtube" }
crossterm = { version = "0.28.1", features = ["event-stream"] }
futures = "0.3.30"
color-eyre = "0.6.3"
open = "5.3.0"
tokio-util = "0.7.11"
