# [package]
# name = "yama"
# edition = "2021"
# version = "0.1.0"

# # found here https://github.com/0atman/noboilerplate/blob/main/scripts/37-functional-rust.md
# [profile.release]
# opt-level = 'z'   # Optimize for size.
# lto = true        # Enable Link Time Optimisation
# # codegen-units = 1 # Reduced to increase optimisations.
# strip = "symbols" # Strip symbols from binary

# [features]
# default = ["youtube", "local", "spotify", "mpris", "mpv"]
# local = ["mpv", "dep:metadata"]
# youtube = ["mpv", "dep:open", "dep:google-youtube3"]
# spotify = ["dep:rspotify", "dep:open"]
# mpris = ["dep:zbus"]
# mpv = ["dep:libmpv"]

[workspace]
members = [
	"protocol",
	"tui",
	"youtube",
]
resolver = "2"
